import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { map } from 'rxjs';
import { decrementaContador, defineContador, IAppState, incrementaContador } from './store/app.state';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})

export class AppComponent {

  private url: string = "https://jsonplaceholder.typicode.com/todos"

  todos: ITodos[] = []
  constructor(
    private store: Store<{ app: IAppState }>,
    private http: HttpClient,
    ){}

  ngOnInit(): void {
    this.http.get<ITodos[]>(this.url)
    .subscribe({
      next: (res) => this.todos = res
    })
  }















  counter$ = this.store
  .select('app')
  .pipe(
    map( e => e.counter)
  )
  ;

  incrementaContador() {
    this.store.dispatch(incrementaContador())
  }

  decrementaContador() {
    this.store.dispatch(decrementaContador())
  }

  defineContador(value: string) {
    const valorTratado = parseFloat(value)
    this.store.dispatch(defineContador( { payload: valorTratado} ))
  }
}

// Generated by https://quicktype.io

export interface ITodos {
  userId:    number;
  id:        number;
  title:     string;
  completed: boolean;
}
